<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPRh2ja5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPRh2ja5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPRh2ja5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPRh2ja5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPRh2ja5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PRh2ja5',
    'container.build_id' => '8d4bc1d1',
    'container.build_time' => 1591659627,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPRh2ja5');
